
version: 2

models:
  - name: raw_fire
    description: "This model contains raw data from the Fire dataset, which includes information about fire incidents."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
